swagger: '2.0'
info:
  title: HR MCP Server
  description: >-
    Allows to manage candidates for specific job roles providing tools to list,
    search, add, update, and remove candidates from a reference list
  version: 1.0.0
host: hr-mcp-ci.ambitiousbush-7fa2fef0.eastasia.azurecontainerapps.io
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: HR MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
securityDefinitions: {}
security: []
